import json
import os
from datetime import datetime
from pathlib import Path
from typing import Optional

from core.models import ScanResult, ScanSummary, Finding, Endpoint


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>ShadowRecon Report - {target}</title>
<style>
* {{ margin: 0; padding: 0; box-sizing: border-box; }}
body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background: #0a0e17; color: #e0e0e0; line-height: 1.6; }}
.container {{ max-width: 1200px; margin: 0 auto; padding: 20px; }}
.header {{ background: linear-gradient(135deg, #0d1b2a 0%, #1b2838 100%); padding: 30px; border-radius: 10px; margin-bottom: 30px; border: 1px solid #1e3a5f; }}
.header h1 {{ color: #00e5ff; font-size: 2em; }}
.header .meta {{ color: #8899aa; margin-top: 10px; font-size: 0.9em; }}
.summary-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 15px; margin-bottom: 30px; }}
.summary-card {{ background: #111927; border-radius: 8px; padding: 20px; border: 1px solid #1e3a5f; text-align: center; }}
.summary-card .number {{ font-size: 2.5em; font-weight: bold; }}
.summary-card .label {{ color: #8899aa; font-size: 0.85em; text-transform: uppercase; margin-top: 5px; }}
.critical {{ color: #ff1744; }} .high {{ color: #ff9100; }} .medium {{ color: #ffd600; }} .low {{ color: #00e5ff; }}
.section {{ background: #111927; border-radius: 8px; padding: 25px; margin-bottom: 30px; border: 1px solid #1e3a5f; }}
.section h2 {{ color: #00e5ff; margin-bottom: 20px; padding-bottom: 10px; border-bottom: 1px solid #1e3a5f; }}
table {{ width: 100%; border-collapse: collapse; }}
th, td {{ padding: 12px 15px; text-align: left; border-bottom: 1px solid #1e3a5f; }}
th {{ color: #00e5ff; font-size: 0.85em; text-transform: uppercase; }}
tr:hover {{ background: rgba(0, 229, 255, 0.05); }}
.badge {{ display: inline-block; padding: 3px 10px; border-radius: 12px; font-size: 0.8em; font-weight: bold; }}
.badge-critical {{ background: #ff1744; color: #fff; }}
.badge-high {{ background: #ff9100; color: #000; }}
.badge-medium {{ background: #ffd600; color: #000; }}
.badge-low {{ background: #00e5ff; color: #000; }}
.badge-info {{ background: #2979ff; color: #fff; }}
.evidence {{ background: #0a0e17; padding: 15px; border-radius: 5px; font-family: 'Cascadia Code', monospace; font-size: 0.85em; overflow-x: auto; white-space: pre-wrap; margin-top: 10px; max-height: 300px; overflow-y: auto; }}
.footer {{ text-align: center; color: #556677; padding: 20px; font-size: 0.85em; }}
</style>
</head>
<body>
<div class="container">
<div class="header">
<h1>🔍 ShadowRecon Security Report</h1>
<div class="meta">
Target: <strong>{target}</strong><br>
Scan Date: {scan_date}<br>
Duration: {duration}s | Session: {session_id}
</div>
</div>

<div class="summary-grid">
<div class="summary-card"><div class="number critical">{critical}</div><div class="label">Critical</div></div>
<div class="summary-card"><div class="number high">{high}</div><div class="label">High</div></div>
<div class="summary-card"><div class="number medium">{medium}</div><div class="label">Medium</div></div>
<div class="summary-card"><div class="number low">{low}</div><div class="label">Low</div></div>
<div class="summary-card"><div class="number">{total_endpoints}</div><div class="label">Endpoints</div></div>
<div class="summary-card"><div class="number">{total_findings}</div><div class="label">Total Findings</div></div>
</div>

<div class="section">
<h2>Endpoints Found</h2>
<table>
<tr><th>URL</th><th>Method</th><th>Type</th><th>Status</th><th>Discovered By</th></tr>
{endpoint_rows}
</table>
</div>

<div class="section">
<h2>Findings</h2>
{finding_cards}
</div>

<div class="section">
<h2>Endpoints by Type</h2>
<table>
<tr><th>Type</th><th>Count</th></tr>
{type_rows}
</table>
</div>

<div class="section">
<h2>Top Risks</h2>
{top_risks_content}
</div>

<div class="footer">
Generated by ShadowRecon on {generated_at}
</div>
</div>
</body>
</html>"""


class ReportGenerator:
    def __init__(self, output_dir: str = "./reports"):
        self.output_dir = output_dir
        Path(output_dir).mkdir(parents=True, exist_ok=True)

    def generate_html(self, result: ScanResult, summary: ScanSummary) -> str:
        severity_colors = {
            "critical": "critical", "high": "high", "medium": "medium",
            "low": "low", "none": "info", "info": "info",
        }

        endpoint_rows = ""
        for ep in sorted(result.endpoints, key=lambda x: x.url):
            ep_type = ep.type.value if hasattr(ep.type, "value") else str(ep.type)
            endpoint_rows += (
                f"<tr><td>{ep.url}</td><td>{ep.method}</td>"
                f"<td>{ep_type}</td><td>{ep.status_code or '-'}</td>"
                f"<td>{ep.discovered_by}</td></tr>\n"
            )

        finding_cards = ""
        for finding in sorted(result.findings, key=lambda x: x.cvss_score or 0, reverse=True):
            badge_class = severity_colors.get(
                finding.severity.value if hasattr(finding.severity, "value") else str(finding.severity),
                "info"
            )
            evidence_html = json.dumps(finding.evidence, indent=2)[:2000] if finding.evidence else "N/A"
            remediation = finding.remediation or "Not specified"
            finding_cards += f"""
            <div style="background: #0f1a2e; padding: 15px; border-radius: 6px; margin-bottom: 15px; border-left: 4px solid var(--{badge_class});">
                <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 10px;">
                    <strong style="font-size: 1.1em;">{finding.title}</strong>
                    <span class="badge badge-{badge_class}">{finding.severity.value if hasattr(finding.severity, 'value') else str(finding.severity).upper()}</span>
                </div>
                <div style="color: #8899aa; font-size: 0.9em; margin-bottom: 10px;">
                    Scanner: {finding.scanner_name} | CVSS: {finding.cvss_score or 'N/A'} | Confidence: {finding.confidence:.0%}
                </div>
                <p>{finding.description}</p>
                <div style="margin-top: 10px;">
                    <strong>Remediation:</strong> {remediation}
                </div>
                <div class="evidence">{evidence_html}</div>
            </div>
            """

        type_rows = ""
        for ep_type, count in sorted(summary.endpoints_by_type.items(), key=lambda x: -x[1]):
            type_rows += f"<tr><td>{ep_type}</td><td>{count}</td></tr>\n"

        top_risks_content = ""
        if summary.top_risks:
            top_risks_content = "<ul>" + "".join(f"<li>{risk}</li>" for risk in summary.top_risks) + "</ul>"
        else:
            top_risks_content = "<p>No critical or high-risk findings.</p>"

        llm_summary_section = ""
        if summary.llm_summary:
            llm_summary_section = f"""
            <div class="section">
            <h2>LLM Executive Summary</h2>
            <div style="color: #e0e0e0; line-height: 1.8;">{summary.llm_summary}</div>
            </div>
            """

        return HTML_TEMPLATE.format(
            target=result.target,
            scan_date=result.started_at.isoformat() if result.started_at else "N/A",
            duration=summary.scan_duration_seconds,
            session_id=result.session_id[:12],
            critical=summary.critical_count,
            high=summary.high_count,
            medium=summary.medium_count,
            low=summary.low_count,
            total_endpoints=summary.total_endpoints,
            total_findings=summary.total_findings,
            endpoint_rows=endpoint_rows,
            finding_cards=finding_cards,
            type_rows=type_rows,
            top_risks_content=top_risks_content,
            generated_at=datetime.utcnow().isoformat(),
            llm_summary_section=llm_summary_section,
        )

    def save_html(self, html: str, session_id: str) -> str:
        path = os.path.join(self.output_dir, f"shadowrecon_report_{session_id[:12]}.html")
        with open(path, "w", encoding="utf-8") as f:
            f.write(html)
        return path

    def generate_json(self, result: ScanResult, summary: ScanSummary) -> str:
        data = {
            "report_version": "1.0",
            "tool": "ShadowRecon",
            "target": result.target,
            "session_id": result.session_id,
            "scan_date": result.started_at.isoformat() if result.started_at else None,
            "duration_seconds": summary.scan_duration_seconds,
            "summary": summary.model_dump(),
            "endpoints": [ep.model_dump() for ep in result.endpoints],
            "findings": [f.model_dump() for f in result.findings],
        }
        return json.dumps(data, indent=2, default=str)

    def save_json(self, json_str: str, session_id: str) -> str:
        path = os.path.join(self.output_dir, f"shadowrecon_report_{session_id[:12]}.json")
        with open(path, "w") as f:
            f.write(json_str)
        return path

    def generate_all(self, result: ScanResult, summary: ScanSummary) -> dict[str, str]:
        html = self.generate_html(result, summary)
        html_path = self.save_html(html, result.session_id)
        json_str = self.generate_json(result, summary)
        json_path = self.save_json(json_str, result.session_id)
        return {"html": html_path, "json": json_path}
